sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
services:
  - docker
before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d