sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
services:
  - docker
before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - |
      if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
        rustup component add clippy
      fi
script:
  - cargo test --all --verbose
  - |
      if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
        cargo clippy --all-targets --all-features -- -D warnings
      fi