sudo: required
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
services:
  - docker
before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - rustup toolchain install nightly-2019-10-30
  - cargo +nightly-2019-10-30 build
  - rustup default nightly-2019-10-30
  - rustup component add clippy
  - cargo install -f cargo-travis;
  - export PATH=$HOME/.cargo/bin:$PATH;
script:
  - RUST_BACKTRACE=1 cargo test --all --verbose
  - cargo clippy --all-targets --all-features -- -D warnings;
after_success:
  - cargo coveralls --exclude-pattern target,clickhouse-rs-cityhash-sys,tests;
